title:              SMC TECH blog
email:              su99king@gmail.com
description:        제작중.
author:             Shin Min Chul
baseurl:            ""
url:                "https://su9king.github.io"

# Social Profiles
twitter_username:   SMC1
github_username:    SMC2
facebook_username:  SMC3
instagram_username:  SMC4
linkedin_username: SMC5

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
